use serde::{Deserialize, Serialize};

#[allow(non_camel_case_types)]
#[derive(Clone, Eq, PartialEq, Hash, Serialize, Deserialize)]
pub enum CacheTableIndex {
  TXID_TO_INSCRIPTION_RECEIPTS,
  SEQUENCE_NUMBER_TO_SATPOINT,
  SAT_TO_SEQUENCE_NUMBER,
  HOME_INSCRIPTIONS,
  INSCRIPTION_ID_TO_SEQUENCE_NUMBER,
  SEQUENCE_NUMBER_TO_CHILDREN,
  SEQUENCE_NUMBER_TO_INSCRIPTION_ENTRY,
  INSCRIPTION_NUMBER_TO_SEQUENCE_NUMBER,
  OUTPOINT_TO_ENTRY,
  BRC20_BALANCES,
  BRC20_TOKEN,
  BRC20_EVENTS,
  BRC20_TRANSFERABLELOG,
  BRC20_INSCRIBE_TRANSFER,
  ORD_TX_TO_OPERATIONS,
  COLLECTIONS_KEY_TO_INSCRIPTION_ID,
  COLLECTIONS_INSCRIPTION_ID_TO_KINDS,
}
